# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

r:
  #- oldrel
  - release
  #- devel

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - testthat
  - covr

r_check_args: --as-cran


matrix:
  include:
  - name: "GeoServer 2.16.0"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.16.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.15.3"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.15.3
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.15.2"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.15.2
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.15.1"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.15.1
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.15.0"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.15.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.3"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.3
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.2"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.2
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.1"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.1
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.0"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.3"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.3
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.2"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.2
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.1"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.1
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.0"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
