# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

services:
  - docker

before_install:
  - docker run --name postgis -e POSTGRES_PASSWORD=geoserver -d mdillon/postgis
  - docker run -it --link postgis:postgres --rm postgres
  - sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
  - docker pull oscarfonts/geoserver
  - docker run -d -p 8080:8080 oscarfonts/geoserver

r:
  - oldrel
  - release
  - devel

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - testthat
  - covr

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
