# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

r:
  #- oldrel
  - release
  #- devel

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - testthat
  - covr

r_check_args: --as-cran


matrix:
  include:
  - name: "GeoServer 2.17.0"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.17.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.16.3"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.16.0
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.15.3"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.15.3
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.14.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.14.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.13.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.13.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.12.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.12.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.11.5"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.11.5
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.10.5"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.10.5
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.9.4"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.9.4
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver
  - name: "GeoServer 2.8.5"
    services: docker
    before_install:
    - docker pull kartoza/postgis
    - docker run -d --name="postgis" kartoza/postgis
    - docker pull oscarfonts/geoserver:2.8.5
    - docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
