# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

services:
  - docker

before_install:
  - docker pull thinkwhere/geoserver
  - mkdir -p ~/geoserver_data
  - docker run --name=geoserver -p 8080:8080 -d -v $HOME/geoserver_data:/opt/geoserver/data_dir -t thinkwhere/geoserver

r:
  - oldrel
  - release
  - devel

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - testthat

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change