# Build
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: R ${{ matrix.config.r }} | GeoServer ${{ matrix.config.geoserver }} | ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', geoserver: 'latest'}
          - {os: ubuntu-latest,   r: 'release', geoserver: 'latest'}
          - {os: ubuntu-latest,   r: 'oldrel-1', geoserver: 'latest'}
    
    env:
      PKG_SYSREQS: false
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      #Docker Geoserver set-up
      - name: Set up GeoServer ${{ matrix.config.geoserver }}
        run: |
          docker run -d --name="postgis" kartoza/postgis:latest
          docker run --link postgis:postgis -d -p 8080:8080 oscarfonts/geoserver:${{ matrix.config.geoserver}}
      
      #R Set-up
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      
      #Install dependencies
      #Install dependencies on Linux
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y make libsodium-dev libicu-dev libxml2-dev libssl-dev pandoc librdf0-dev libnode-dev libcurl4-gnutls-dev libsecret-1-dev
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML
          needs: check
          cache-version: 5
      
      #Check R Package
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          artifact-name: geosapi_r-${{ matrix.config.r }}_geoserver-${{matrix.config.geoserver}}_${{ matrix.config.os }}-results
